### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by dashaun** [madduci/kind-with-mesh#2]
First, let me say thank you so much for making this repo public and [sharing it with me](https://x.com/m_adduci/status/1752554279120830801?s=20)!

I immediately did a [live stream](https://www.youtube.com/live/dy1RhhD71R0?si=OnN7gG8dqhgrHcGt) and took it for a spin!

I ran into an issue, and I think its because I'm on Apple silicon (M1).

@pacphi joined me on the stream, and had X86 ready to try it with me.  And it worked for him.

I'm very impressed!

I will definitely keep you posted if I take this concept any further!

**Comment by madduci** [comment]
Hi

Thanks for using the project, I'm happy you might find it useful.

Concerning the ARM64 support, it seems like arm64  images for KIND are
available (e.g.
https://hub.docker.com/layers/kindest/node/v1.26.6/images/sha256-26ae311549359a62de298e6a99daff1b5cb4806161ade7816b82f23ab0489622?context=explore&tab=vulnerabilities),
so the command line tool as well:
https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

Unfortunately I don't own an Apple Silicon myself and can't reproduce the
issue, but could you please share any output logs for the problem you are
facing?

Many thanks

**Comment by dashaun** [comment]
Very interesting!
![Screenshot 2024-01-31 at 01 35 00](https://github.com/madduci/kind-with-mesh/assets/826271/808b84c7-05b1-4020-8188-da5c7df40350)

**Comment by dashaun** [comment]
[describe.txt](https://github.com/madduci/kind-with-mesh/files/14108658/describe.txt)

**Comment by madduci** [comment]
Thanks for sharing, it seems like a kind of limitation / requirement of Cilium and it might have to do with the MacOS Kernel.

Here I've found an issue about it: https://github.com/cilium/cilium/issues/30278

The suggested "solution" is to ditch Docker Desktop on Mac and use another runtime: 

> Closing since it seams to be a problems with docker desktop, and switching away from that, solves the problem.

https://github.com/cilium/cilium/issues/30278#issuecomment-1911651545

**Comment by madduci** [comment]
I am closing this issue as it's a Docker Desktop/Cilium bug, not a real issue with this terraform project.
